version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
     - "80:80"
     - "443:443"
    restart: always
    volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d
     - ./nginx/ssl/private:/etc/ssl/private/
     - ./nginx/ssl/public:/etc/ssl/public/
     - ./nginx/content/:/usr/share/nginx/html