version: '3'
services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database

volumes:
  mysql: